### PR TITLE
DISABLED_AUTHENTICATION, DISABLED_REGISTRATION are now callable (?)

### PR DESCRIPTION
**Pull request by knivets**
This is probably not what you want because you said to use the design of `get_broker`, but I'm not sure how can I apply this here, so please let me know what should be done here.

### CODE REVIEW

**Comment by smirolo** [comment]
1. In all files where `DISABLED_AUTHENTICATION` and `DISABLED_REGISTRATION` are used, replace by `get_disabled_authentication` and `get_disabled_registration` respectively.

2. The code of `get_disabled_authentication` should be like:

     def get_disabled_authentication():
         if isinstance(organization, six.string_types):
             return import_string(settings.DISABLED_AUTHENTICATION_CALLABLE)()
         return bool(settings.DISABLED_AUTHENTICATION_CALLABLE)

The default in settings.py should read like:

      'DISABLED_AUTHENTICATION_CALLABLE': False

This will be used in testsite/settings.py like so for example:

     SIGNUP = {
         'DISABLED_AUTHENTICATION_CALLABLE': 'testsite.multitier.get_disabled_authentication'
     }

**Comment by smirolo** [comment]
It might actually be best to keep the name of the settings as `DISABLED_AUTHENTICATION`, just support a callable as an option. So testsite/settings.py could be:

    SIGNUP = {
        'DISABLED_AUTHENTICATION': True
    }

or 

    SIGNUP = {
        'DISABLED_AUTHENTICATION': 'testsite.multitier.get_disabled_authentication'
    }

Sounds better.

**Comment by knivets** [comment]
what about `ENABLE_AUTHENTICATION`?

**Comment by smirolo** [comment]
Authentication is enabled by default (registration/login are the whole point of the project). Auth might need to be disabled temporary as a stop-gap measure because of some behavior happening in production (ex: bots trying to break into various accounts).
That's the reason the settings is called `DISABLE_*`. The default is enabled. If the default was disabled, then it would make sense to call the variable `ENABLE_*`.

**Pull request merged**
